server:
  servlet:
    context-path: /security
  port: 8888


#spring:
#  security:
#    user:
#      name: oyc
#      password: 123456
spring:
  datasource:
    url: jdbc:mysql://146.56.192.87:3306/oyc_security?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: oyc
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
    root: debug
